# -*- coding: utf-8 -*-
"""Second développement, pour dépasser 60 pages sans changer le plan."""


def _ps(doc, add_p, paragraphs):
    for text in paragraphs:
        add_p(doc, text)


def plus_1(doc, add_h, add_p, add_table):
    add_h(doc, "1.15 Trois situations de menace", 2)
    _ps(doc, add_p, [
        "La première situation est la copie de la base et du disque des blobs. Un administrateur système, ou une personne qui vole une sauvegarde de machine, obtient les tables et les fichiers chiffrés. Il lit les adresses, les noms logiques, les tailles, les dates, les rôles et les empreintes. Il lit aussi les nonces et les clés enveloppées. Il ne lit pas le mot de passe, seulement son empreinte de connexion, et il ne lit pas la clé maître, qui n'a jamais été écrite. Sans le mot de passe d'un utilisateur, PBKDF2 ne peut pas être recalculé jusqu'à la bonne clé, sinon au prix d'une recherche dont chaque essai coûte les itérations prévues (Turan, Barker, Burr et Chen, 2010 ; Moriarty, Kaliski et Rusch, 2017). Les fichiers des autres comptes restent fermés de la même façon, un mot de passe ne déverrouille que son sel.",
        "La deuxième situation est l'écoute du réseau. Entre le navigateur et l'API, un observateur voit une session TLS. Il ne voit pas le mot de passe, ni le jeton, ni le blob, tant que le canal est authentifié et confidentiel (Rescorla, 2018). Si le canal était absent, le jeton pourrait être rejoué et le blob copié. Le blob copié resterait chiffré, mais le jeton ouvrirait le compte. La revue sépare donc les deux protections : TLS protège la session en transit, AES-GCM protège le fichier au repos (Dworkin, 2007). Un mémoire qui ne citerait que l'un des deux laisserait un trou dans le modèle de menace du chapitre 1.",
        "La troisième situation est le poste déverrouillé. L'utilisateur s'est connecté, la clé maître est en mémoire, une restauration produit le clair dans le navigateur. Toute personne qui contrôle alors ce navigateur voit ce que l'utilisateur voit. Aucun chiffrement de coffre ne protège l'écran d'une session ouverte. Le système réduit la fenêtre en proposant la déconnexion, qui oublie le jeton local et invalide la session serveur, et en rendant les miniatures optionnelles, afin de ne pas déchiffrer une image sans un choix explicite. Cette situation fixe une limite honnête : ARSAVE protège le dépôt distant, il ne protège pas un poste déjà compromis après connexion (Anderson, 2020).",
        "Ces trois situations seront reprises implicitement par les essais. L'essai qui refuse un mot de passe faux vérifie que la deuxième barrière, l'authentification, ne s'ouvre pas par hasard. L'essai qui restaure un fichier vérifie que le clair n'apparaît que sur le client. L'essai d'administration vérifie qu'un rôle élevé ne contourne pas la première situation : la copie des tables, même lue par l'admin via l'écran, ne montre pas le contenu. Écrire les situations avant les diagrammes évite d'ajouter, au chapitre 3, un cas « l'administrateur lit les fichiers », qui contredirait la menace retenue.",
    ])
    add_h(doc, "1.16 Paramètres cryptographiques et ce qu'ils engagent", 2)
    _ps(doc, add_p, [
        "Plusieurs nombres structurent la construction. La clé AES fait 256 bits, taille prévue par FIPS 197 (NIST, 2001). La clé de fichier est tirée aléatoirement à chaque dépôt, puis jetée du serveur : seule son enveloppe reste. Le sel fait 32 octets, soit 256 bits, ce qui rend négligeable le risque que deux utilisateurs reçoivent le même sel dans un déploiement de cette taille. Le nombre d'itérations PBKDF2 est 120 000, avec HMAC-SHA256. Ce n'est pas une constante magique : c'est un coût accepté au moment de la connexion, sur le poste, pour ralentir une recherche de mot de passe si le sel et l'empreinte venaient à être copiés (Bonneau, Herley, van Oorschot et Stajano, 2012). Le changer plus tard exige que tous les clients utilisent la même valeur, sinon la clé redérivée ne déchiffrerait plus les enveloppes.",
        "L'encodage base64 des nonces et de la clé enveloppée est un choix de transport, décrit par Josefsson (2006). Il permet de placer des octets dans du JSON ou dans un champ de formulaire sans les casser. Il n'ajoute pas de secret. L'empreinte SHA-256 est codée en hexadécimal sur 64 caractères, taille fixe, ce qui simplifie la colonne MySQL et la comparaison. Elle porte sur le ciphertext. La comparer au clair serait inutile pour le serveur, qui ne doit pas avoir le clair, et trompeuse pour le client, qui veut savoir si le blob reçu est celui qui a été envoyé.",
        "Le jeton de session est aléatoire et long. Seule son empreinte est conservée, sur 64 caractères hexadécimaux également. Deux sessions du même utilisateur peuvent coexister, par exemple un navigateur et un autre poste, chacune avec son jeton. Invalider l'une ne dérive pas l'autre. Cette propriété compte pour la déconnexion : quitter le navigateur ne doit pas exiger d'effacer une clé serveur qui n'existe pas, mais doit empêcher la réutilisation de ce jeton (OWASP Foundation, s. d.-c). La clé maître, elle, n'est pas un jeton. Elle ne s'envoie pas, elle ne se stocke pas dans la table sessions, et elle meurt avec la mémoire du client.",
        "Ces paramètres engagent la maintenance. Une itération future peut augmenter le nombre d'itérations, à condition de garder l'ancien coût pour les comptes déjà créés ou de prévoir une migration. Elle peut changer la présentation des écrans sans toucher aux colonnes. Elle ne peut pas « simplifier » en stockant la clé maître pour éviter de redemander le mot de passe : ce serait annuler l'exigence principale de la revue. Le chapitre 4 a donc le droit de coder ces nombres, il n'a pas le droit de les remplacer par un stockage du secret en base.",
    ])
    add_h(doc, "1.17 Place du client web dans la revue", 2)
    _ps(doc, add_p, [
        "Le client web n'est pas un détail de présentation ajouté après coup. C'est la partie du système que l'utilisateur et l'administrateur voient. Flutter est retenu parce qu'une même base d'écrans sert le navigateur et, si on le lance, un poste Android (Flutter team, s. d.). Pour le mémoire, la vérification se fait dans le navigateur. Cette décision a trois conséquences théoriques, déjà posées mais qu'il faut tenir jusqu'au chapitre 4. Premièrement, le sélecteur de fichiers fournit des octets, pas un chemin durable. Deuxièmement, le téléchargement du clair repasse par le navigateur. Troisièmement, le thème, sombre ou clair, est un état d'interface local.",
        "Le bleu de nuit n'est pas un argument de sécurité. C'est le thème par défaut, choisi pour l'usage prolongé du coffre, avec une alternative claire. Le lier à la confidentialité serait une confusion. La confidentialité, dans ce mémoire, se mesure à l'absence de clair sur le serveur et à l'absence de clé maître en base. L'apparence se mesure à la lisibilité des cartes, des graphiques et des messages. ISO/IEC 25010 sépare justement l'utilisabilité et la sécurité (ISO/IEC, 2011). Les garder séparées évite qu'un changement de couleur soit décrit comme une mesure de protection.",
        "Les graphiques du tableau de bord relèvent de la même distinction. Un histogramme des dépôts et une répartition par genre aident à voir l'activité. Ils lisent des métadonnées et des opérations, jamais le clair. Un camembert qui exigerait d'ouvrir les fichiers pour les classer contredirait le modèle. Le genre est donc déduit du type MIME et du nom, données que le serveur connaît déjà parce que l'utilisateur les a envoyées comme métadonnées. Cette précision prépare la classe Fichier : mime et logical_name sont lisibles, le blob ne l'est pas.",
    ])


def plus_2(doc, add_h, add_p, add_table):
    add_h(doc, "2.11 Parcours de dépôt, produit par produit", 2)
    _ps(doc, add_p, [
        "Dans Drive, l'utilisateur ouvre le navigateur, s'identifie auprès du compte Google et dépose un fichier. Le service le rend disponible sur d'autres appareils du même compte. La documentation de sécurité décrit la protection de la plateforme et des comptes (Google, s. d.). Elle ne décrit pas une clé de contenu détenue seulement par l'utilisateur avant l'envoi. Pour le scénario « déposer sans que l'hébergeur puisse lire », le parcours s'arrête donc au premier pas : le clair quitte le poste. Le reste du parcours, reprise et corbeille, est au contraire très complet. L'analyse ne le nie pas. Elle dit seulement qu'il ne comble pas l'écart retenu.",
        "Dropbox et OneDrive suivent un parcours analogue : identifiant du service, dépôt du fichier, reprise, historique ou versions selon l'offre, corbeille (Dropbox, s. d. ; Microsoft, s. d.). Leur force, pour un usage courant, est précisément cette continuité. Leur modèle de confiance place l'opérateur du côté du contenu. Un mémoire qui proposerait de « faire comme Dropbox, avec une option de chiffrement » reconstituerait le cas optionnel que le chapitre 1 a refusé. La comparaison sert à écarter cette option, pas à copier l'interface.",
        "MEGA annonce un parcours où le chiffrement est lié au compte utilisateur de telle sorte que le service insiste sur le contrôle de la clé par l'utilisateur (Mega Ltd, s. d.). Le dépôt depuis le web existe. La reprise existe. Pour l'hébergement du mémoire, toutefois, on ne déploie pas MEGA sur la machine de démonstration pour y brancher le client Flutter. Le parcours intéresse comme preuve qu'un chiffrement côté client est crédible aux yeux d'un service public. Il ne fournit pas le schéma de tables, ni les rôles admin locaux, que le chapitre 3 doit dessiner.",
        "Nextcloud permet d'installer le service, de créer des comptes et de déposer un fichier par le web (Nextcloud GmbH, s. d.). C'est le parcours le plus proche d'un déploiement local. Si l'on reste au stockage par défaut, le fichier sur le serveur n'est pas dans la situation « clé seulement chez l'utilisateur ». Si l'on active le chiffrement de bout en bout documenté à part, on se rapproche de l'écart, au prix d'un mode qui n'est pas celui de chaque dépôt ordinaire. ARSAVE inverse la charge : il n'y a pas de dépôt ordinaire en clair. Le parcours nominal du chapitre 3 commence par la lecture des octets et le chiffrement, avant toute requête de sauvegarde.",
    ])
    add_h(doc, "2.12 Reprise, perte du poste et administration", 2)
    _ps(doc, add_p, [
        "La reprise révèle une tension que le dépôt cache. Si la clé ne quitte jamais le poste et que le poste est perdu, le fichier distant est inutile sans un secret que l'utilisateur peut ressaisir. ARSAVE résout cette tension, dans le scénario nominal, par le mot de passe et le sel : un nouveau navigateur, après connexion, redérive la même clé maître et ouvre les enveloppes. Il ne résout pas la perte du mot de passe. Les produits généralistes la résolvent mieux, parce qu'ils peuvent rendre le clair à qui prouve son identité auprès d'eux. Cette facilité est l'envers de leur modèle de confiance. Le chapitre 2 la reconnaît comme un avantage des systèmes existants, puis ne la reprend pas, parce qu'elle contredit l'exigence de clé absente du serveur.",
        "L'administration révèle une seconde tension. Un outil hébergé a besoin de quelqu'un qui crée des rôles, retire un compte et regarde si le service est utilisé. Nextcloud et les offres d'entreprise le font largement. Si cet administrateur peut aussi ouvrir les fichiers, la frontière demandée par le mémoire disparaît. ARSAVE garde l'administration des comptes et des indicateurs, et retire la lecture. Le parcours admin s'arrête à la liste, au rôle et à la suppression. Il ne continue pas vers un bouton de téléchargement du coffre d'autrui. Cette coupure est l'écart le plus net avec une administration d'entreprise classique, et elle doit rester visible sur le diagramme de cas : l'acteur Administrateur n'est pas relié à Restaurer pour les fichiers des autres.",
        "La corbeille, enfin, est un point d'accord. Tous les systèmes examinés évitent, d'une manière ou d'une autre, que le premier clic de suppression soit définitif. ARSAVE reprend l'accord : écarter, remettre, puis purger. La purge emporte le blob chiffré. Il n'y a pas de « corbeille lisible par l'opérateur », puisque l'opérateur ne lisait déjà pas le clair. Le parcours de suppression est donc plus simple à comparer que le parcours de dépôt : la différence n'est pas le geste de l'utilisateur, elle est le fait que le fichier écarté reste un ciphertext.",
    ])
    add_h(doc, "2.13 Décision transmise à la conception", 2)
    _ps(doc, add_p, [
        "La décision tient en une phrase opératoire. Le système proposé offre le parcours web dépôt, reprise, corbeille et comptes, et il impose le chiffrement avant l'envoi sur l'unique parcours de dépôt. Tout ce qui, chez les produits étudiés, dépend de la lecture du clair par le service est hors périmètre : recherche dans le contenu, aperçu serveur, partage d'un lien qui révèlerait le fichier sans la clé, récupération du coffre par l'administrateur. Tout ce qui peut se faire avec des métadonnées ou avec un déchiffrement local est dans le périmètre : nom, type, taille, genre, miniature locale, historique, graphiques, rôles.",
        "Cette phrase devient le test de chaque cas du chapitre 3. Si un cas exige que l'API comprenne le contenu, il est rejeté. Si un cas n'exige que le nom et le statut, il est accepté. La miniature est le cas limite, et elle passe parce que le déchiffrement a lieu dans le navigateur de la personne qui connaît le mot de passe. Le classement par genre passe parce qu'il utilise le type annoncé. L'histogramme passe parce qu'il compte des opérations. La suppression d'un compte passe parce qu'elle détruit des blobs sans les ouvrir. Aucune de ces acceptations ne réintroduit Drive, Dropbox, OneDrive, MEGA ou Nextcloud comme modèle à implémenter. Ils restent la matière du chapitre 2.",
    ])


def plus_3(doc, add_h, add_p, add_table):
    add_h(doc, "3.13 Scénario nominal 1 rédigé en étapes", 2)
    _ps(doc, add_p, [
        "Le scénario 1 est l'authentification réussie. Il correspond à la figure 2. Il est écrit ici en étapes numérotées afin qu'un lecteur puisse suivre le dessin sans deviner l'ordre. Étape 1 : l'utilisateur ouvre le client web et saisit son adresse, son mot de passe et laisse le poste être présenté par son identifiant d'appareil. Étape 2 : le client envoie ces éléments à l'API par la route de connexion. Il n'envoie pas de clé. Étape 3 : l'API retrouve le compte et compare l'empreinte du mot de passe. Étape 4 : elle enregistre l'appareil s'il est nouveau, ou met à jour sa date de vue. Étape 5 : elle crée une session, conserve l'empreinte du jeton et la date de fin, et renvoie le jeton, l'expiration, le profil et le sel. Étape 6 : le client dérive la clé maître localement et ouvre le tableau de bord. Étape 7 : les appels suivants présentent le jeton, jusqu'à déconnexion ou expiration.",
        "Chaque étape a un responsable unique. Les étapes 1 et 6 sont du côté de l'acteur et du client. Les étapes 3 à 5 sont du côté de l'API et de la base. Aucune étape ne dit « le serveur calcule la clé maître ». Si une réalisation du chapitre 4 introduisait cette étape, elle serait non conforme au scénario, même si les écrans restaient identiques. C'est le sens d'un scénario dans UP : il contraint la construction plus sûrement qu'une maquette d'écran (Jacobson, Booch et Rumbaugh, 1999 ; Cockburn, 2001).",
        "Le scénario s'arrête lorsque le tableau de bord est accessible. Il ne déroule pas le dépôt. Enchaîner les deux sur une seule figure rendrait le dessin illisible et mélangerait deux buts. Le lien entre eux est la précondition du second : session ouverte et clé maître présente. Cette précondition est vraie seulement si le scénario 1 s'est terminé sans extension. Après un mot de passe faux, la précondition est fausse, et le scénario 2 ne démarre pas.",
    ])
    add_h(doc, "3.14 Scénario nominal 2 rédigé en étapes", 2)
    _ps(doc, add_p, [
        "Le scénario 2 est la sauvegarde réussie. Il correspond à la figure 3 et au chemin positif de la figure 4. Étape 1 : l'utilisateur, déjà authentifié, choisit un fichier de n'importe quel type. Étape 2 : le client lit les octets en mémoire. Étape 3 : il tire une clé de fichier et les nonces, chiffre en AES-256-GCM, enveloppe la clé avec la clé maître et calcule l'empreinte du ciphertext. Étape 4 : il envoie le blob et les champs, avec le jeton. Étape 5 : l'API vérifie la session et l'empreinte, écrit le blob, crée ou complète le fichier logique, ajoute la version, pointe la version courante et journalise le succès. Étape 6 : le client affiche le fichier dans le coffre et une ligne d'activité. Le clair n'apparaît dans aucune de ces étapes côté serveur.",
        "La restauration n'est pas un troisième scénario dessiné, mais elle se raconte dans le même style pour que la fiche 3.8.4 soit aussi précise. Étape 1 : l'utilisateur demande la restauration. Étape 2 : l'API vérifie le jeton et la chaîne fichier-propriétaire, puis renvoie le blob et les champs cryptographiques. Étape 3 : le client vérifie l'empreinte, ouvre l'enveloppe, déchiffre et déclenche le téléchargement du clair. Étape 4 : une opération de téléchargement est journalisée. Si l'étape 3 échoue sur l'empreinte, le téléchargement du clair n'a pas lieu. L'ordre compte : vérifier avant d'ouvrir, afin de ne pas traiter un blob substitué comme un fichier légitime (NIST, 2015 ; Dworkin, 2007).",
        "La mise en corbeille est plus courte. Étape 1 : l'utilisateur écarte le fichier. Étape 2 : l'API vérifie l'appartenance et change le statut. Étape 3 : le coffre actif ne le liste plus, la corbeille le liste. La purge ajoute l'effacement du blob. Aucune de ces étapes n'exige la clé maître, parce qu'elles ne touchent pas le clair. C'est une conséquence utile du modèle : on peut ranger ou détruire un fichier chiffré sans savoir le lire. L'administrateur qui supprime un compte entier utilise la même propriété.",
    ])
    add_h(doc, "3.15 Attributs du domaine et règles d'intégrité", 2)
    _ps(doc, add_p, [
        "Utilisateur.email est unique. Deux inscriptions ne partagent pas une adresse. Utilisateur.role ne prend que les valeurs simple ou admin. Utilisateur.kdf_salt est obligatoire dès la création : un compte sans sel ne pourrait pas redériver de clé, et le scénario 1 échouerait à l'étape 6 même avec un bon mot de passe. Utilisateur.password_hash est obligatoire et ne sert qu'à l'étape 3 du scénario 1.",
        "Session.token_hash est unique. Deux sessions ne partagent pas la même empreinte. Session.expires_at est obligatoire. Une session sans fin ne réaliserait pas l'exigence de session révocable par le temps. Session peut référencer un appareil nul si l'information manque, mais le parcours web nominal renseigne l'appareil. Appareil.device_uid est unique pour un utilisateur donné : le même poste qui se reconnecte ne crée pas une infinité de lignes.",
        "Fichier.logical_name est le nom montré. Il n'est pas une clé primaire : deux fichiers peuvent porter le même nom, l'identifiant les distingue. Fichier.status commande les listes. Fichier.current_version_id désigne la version que la restauration prend si aucune version n'est précisée. VersionFichier.version_number croît pour un même fichier. Le couple fichier et numéro est unique. VersionFichier.size_bytes mesure le ciphertext, pas le clair : le tableau de bord qui parle de volume parle donc du volume stocké, ce qui est cohérent avec ce que le serveur sait mesurer.",
        "Operation.type distingue au moins le dépôt, le téléchargement, la corbeille, la remise et la purge. Operation.status distingue le succès, l'échec, le démarrage ou l'interruption, selon ce que la construction a effectivement écrit. Operation.message reste court : c'est un texte d'historique, pas un journal système illimité. Operation.file_id est vide lorsque l'action ne vise pas un fichier. Ces règles tiennent dans le diagramme de classes par les attributs et les cardinalités. Les répéter en phrases sert la lecture orale du mémoire, lorsque la figure 5 est projetée à côté du texte (Rumbaugh, Jacobson et Booch, 2004).",
        "Intégrité référentielle. Supprimer un utilisateur supprime ses sessions, appareils, fichiers, versions et opérations. Supprimer un fichier supprime ses versions. Effacer une version sans effacer le blob serait une faute de réalisation : la règle de domaine est que le chemin storage_path ne survit pas à la version. Le chapitre 4 doit donc effacer le fichier disque dans la même action que la ligne. Cette phrase relie la classe à une responsabilité physique, sans ajouter une classe Disque sur la figure 5. Le disque est le support de l'attribut storage_path, pas un concept métier nouveau.",
    ])
    add_h(doc, "3.16 Règles de cohérence entre les dessins", 2)
    _ps(doc, add_p, [
        "Quatre règles empêchent les figures de diverger. Règle A : tout message de la figure 2 ou de la figure 3 correspond à une étape des sections 3.13 et 3.14. Règle B : toute décision de la figure 4 correspond à une extension du cas sauvegarder. Règle C : toute classe de la figure 5 correspond à une table de l'annexe C, à l'exception des services de construction qui ne sont pas du domaine. Règle D : toute inclusion dessinée sur la figure 1 est obligatoire dans le scénario nominal. L'inclusion du chiffrement satisfait la règle D. L'absence de lien entre l'administrateur et la restauration des fichiers d'autrui satisfait la même règle par le silence : ce qui n'est pas inclus n'est pas un chemin caché.",
        "Si une soutenance demande « où est le chiffrement sur la séquence », la réponse est l'étape 3 du scénario 2, avant l'envoi. Si l'on demande « où est l'échec », la réponse est la figure 4, pas la figure 3. Si l'on demande « où est la clé maître », la réponse est la mémoire du client après l'étape 6 du scénario 1, et nulle part dans la figure 5. Ces trois réponses tiennent en une page parce que les dessins ont été limités à UP et à UML. Ajouter un autre formalisme obligerait à réécrire les règles de cohérence. Le mémoire ne le fait pas.",
    ])


def plus_4(doc, add_h, add_p, add_table):
    add_h(doc, "4.12 Déroulé d'une session sur le client web", 2)
    _ps(doc, add_p, [
        "Une session de vérification commence par l'ouverture du client dans le navigateur, API déjà joignable. L'utilisateur crée un compte, puis se connecte. Le tableau de bord s'affiche, encore presque vide : les indicateurs sont à zéro ou proches de zéro, l'historique est court, les graphiques n'ont pas encore de dépôts. Ce premier écran réalise la fin du scénario 1. Il ne montre pas de fichier, ce qui est correct : le scénario 2 n'a pas eu lieu.",
        "L'utilisateur passe au coffre et dépose un texte, puis une image, puis un autre type. Après chaque dépôt, le fichier apparaît avec son genre. L'image peut montrer une miniature si l'aperçu est actif et si la taille le permet. Le texte et l'archive montrent leur genre sans aperçu du contenu. Le tableau de bord, rouvert, compte les fichiers, distingue le volume stocké et commence à remplir la répartition et l'histogramme. L'activité liste les dépôts en succès. Ce parcours réalise le scénario 2 plusieurs fois et le cas de consultation du tableau de bord.",
        "L'utilisateur ouvre un fichier et le restaure. Le navigateur télécharge le clair. Il écarte ensuite un fichier, le voit dans la corbeille, le remet, puis en purge un autre. Chaque geste a une ligne d'historique. Il ouvre les réglages, passe au thème clair, revient au thème sombre, coupe les miniatures et change son nom. Seul le nom provoque une écriture de compte. Il se déconnecte. Une tentative d'accès au coffre sans nouvelle connexion échoue. Ce déroulé tient les cas secondaires dans la même session que les cas principaux, ce qui correspond à la façon dont le client web est réellement organisé : une coque, quatre destinations, et la corbeille atteinte depuis le tableau de bord ou les réglages.",
        "Avec le compte administrateur de démonstration, le même genre de session montre en plus l'entrée d'administration. La liste des comptes contient au moins l'administrateur et le compte créé plus haut. Basculer le rôle du compte de test, puis le supprimer, retire ses fichiers. Le compte administrateur ne se supprime pas lui-même. À aucun moment cet écran ne propose le contenu déchiffré. Le déroulé admin est donc plus court que le déroulé utilisateur, et c'est voulu : le cas « gérer les comptes » a moins d'étapes que « sauvegarder », parce qu'il ne chiffre rien.",
    ])
    add_h(doc, "4.13 Contrôles présents dans la construction", 2)
    add_table(
        doc,
        ["Contrôle", "Où il est réalisé", "Ce qu'un essai doit voir"],
        [
            ["Unicité de l'adresse", "Inscription", "E02 refuse le doublon"],
            ["Empreinte du mot de passe", "Connexion", "E04 ne ouvre pas de session"],
            ["Jeton et expiration", "Chaque route métier", "E22 refuse après déconnexion"],
            ["Appartenance du fichier", "Lecture, corbeille, téléchargement", "Un autre compte est refusé"],
            ["Empreinte du blob", "Dépôt et restauration", "E10 ne produit pas le clair"],
            ["Rôle admin", "Routes /admin", "E17 cache l'entrée"],
            ["Dernier admin", "Changement de rôle et suppression", "E21 refuse"],
            ["Effacement des blobs", "Purge et suppression de compte", "E12 et E20"],
            ["Message visible", "Client web", "Aucune erreur silencieuse sur l'action tentée"],
        ],
    )
    add_p(doc, "Tableau 7. Contrôles de construction et essais associés", italic=True, center=True, first_line=False)
    _ps(doc, add_p, [
        "Le tableau 7 est la liste de contrôle de la fin de construction. Il ne remplace pas le code. Il dit quel comportement observer. Un contrôle coché dans le code mais invisible à l'essai E correspondant serait un défaut d'interface, parce que le mémoire a exigé des messages. Un essai qui réussit alors que le contrôle est absent serait un défaut de serveur. Les deux côtés, client et API, portent donc une partie de la preuve. Le client ne peut pas, par exemple, garantir à lui seul qu'un autre compte ne recevra pas un fichier : seul l'API, qui tient la session, peut refuser. Le client peut garantir qu'il ne postera pas de clair, parce que le chiffrement est devant l'envoi. La répartition suit les responsabilités du chapitre 3.",
        "Les contrôles cryptographiques ne se voient pas sur l'écran autrement que par leurs effets. L'utilisateur ne voit pas le nonce. Il voit que la restauration rend son fichier, et que l'administration ne le rend pas à quelqu'un d'autre. Pour aller plus loin, la revue de construction regarde les colonnes de l'annexe H et confirme l'absence de clé maître. Cette revue de schéma fait partie de l'itération, au même titre qu'un essai de clic. Elle est rapide, et elle protège contre une régression qui ajouterait une colonne « pour dépanner ». Le dépannage d'un coffre ne passe pas par l'écriture du secret en base.",
    ])
    add_h(doc, "4.14 Limites relues avant la transition", 2)
    _ps(doc, add_p, [
        "La première limite est le changement de mot de passe. Le mécanisme existe, le sel change, les anciens fichiers ne se rouvrent pas. Une transition correcte ajouterait, avant de remplacer le sel, un parcours où le client, encore en possession de l'ancienne clé, réenveloppe chaque clé de fichier. Ce parcours n'est pas dessiné. Le dire clairement évite de laisser l'annexe des routes suggérer que la réinitialisation est un scénario nominal équivalent à la connexion.",
        "La deuxième limite est l'administration incomplète par rapport à l'expression « tout gérer ». L'écran liste, change le rôle et supprime. Il ne crée pas un compte et ne force pas un mot de passe. L'inscription publique couvre la création. Une itération suivante peut ajouter ces actions sans nouveau concept de classe : Utilisateur existe déjà. Elle ne devra pas, à cette occasion, ajouter la lecture des fichiers. La limite porte sur l'ampleur de l'écran, pas sur la frontière de confidentialité, qui est déjà tenue.",
        "La troisième limite est l'aperçu. Seules certaines images sont déchiffrées pour une miniature, et seulement si le réglage le permet. Les autres genres sont reconnus par une indication de type. Il n'y a pas de lecteur vidéo intégré ni de visionneuse de documents. La restauration reste le moyen d'obtenir le fichier. Cette limite protège le périmètre : un lecteur complet inviterait à déchiffrer de plus en plus de formats dans le navigateur, ce qui est possible, mais ce n'est pas nécessaire pour démontrer les scénarios 1 et 2.",
        "La quatrième limite est le déploiement. Le système est montré en local, avec une base et une API sur la machine de développement. Le mémoire n'affirme pas une mise en production, une sauvegarde chiffrée des blobs hors de la machine, ni une politique d'organisation au sens d'ISO/IEC 27001. Il affirme que les cas construits fonctionnent dans cet environnement et que les choix de conception restent lisibles. La transition, au sens de Kruchten (2004), commencerait après cela : durcir l'hébergement, revoir les itérations de mot de passe, compléter l'écran admin. Elle n'est pas le chapitre présent. Le chapitre présent s'arrête lorsque les scénarios nominaux ont une réalisation vérifiable.",
    ])
    add_h(doc, "4.15 Ce que la construction confirme des figures", 2)
    _ps(doc, add_p, [
        "La figure de cas d'utilisation est confirmée si chaque ellipse a un chemin dans le client web. L'inscription et la connexion ont leurs formulaires. La sauvegarde a le sélecteur du coffre, et le chiffrement n'est pas un bouton séparé : il est inclus dans l'envoi, comme l'inclusion le demande. La restauration est l'action du détail de fichier. L'historique, la corbeille et le tableau de bord ont leurs destinations. L'administration n'apparaît que pour le rôle prévu. Cette correspondance est le premier contrôle visuel de la construction. Un écran orphelin, sans cas, serait le signe que la construction a dérivé. Un cas sans écran serait le signe qu'elle est incomplète.",
        "La figure de séquence de l'authentification est confirmée par l'ordre réel des appels. Le mot de passe part vers l'API. Le sel en revient. La dérivation a lieu ensuite, sur le poste. On le vérifie en relisant la réponse : elle contient le jeton et le sel, elle ne contient pas une clé de 256 bits prête à chiffrer. La figure de séquence de la sauvegarde est confirmée par l'ordre inverse du contenu : les octets sont chiffrés avant le multipart. Le serveur reçoit un blob et des champs. Il ne reçoit pas le fichier original. Si un journal de développement montrait le clair dans le corps de la requête, la figure 3 serait contredite, quel que soit le soin apporté aux écrans.",
        "La figure d'activité est confirmée par les deux refus déjà prévus. Un échec avant l'envoi, par exemple un fichier que le navigateur ne remet pas, s'arrête sur un message et ne crée pas de version. Un échec de l'API, par exemple une session absente, s'arrête aussi sur un message. Le chemin vertical « oui, puis oui » est le dépôt ordinaire du coffre. Il n'existe pas de troisième chemin qui enregistrerait un succès sans blob. Cette absence est voulue. Elle réalise le défaut sûr retenu dans la revue : en cas de doute, le coffre reste dans l'état précédent (Saltzer et Schroeder, 1975).",
        "La figure de classes est confirmée par le schéma. On y retrouve l'utilisateur, ses sessions, ses appareils, ses fichiers, les versions et les opérations, avec les cardinalités annoncées. On n'y retrouve pas de table de clé maître. La construction peut ajouter des index, des dates de mise à jour ou une table de réinitialisation de mot de passe : ce sont des détails de réalisation. Elle ne peut pas ajouter une colonne qui stockerait le secret de chiffrement sans sortir du modèle. Le tableau 4 reste donc le critère de relecture du schéma à la fin du chapitre, au même titre que les essais de clic.",
        "Prises ensemble, ces confirmations ferment la boucle du Unified Process pour cette itération. L'inception avait fixé l'écart. L'élaboration l'a dessiné. La construction l'a rendu exécutable sur le client web. La transition n'est pas commencée : les limites de mot de passe, d'aperçu et d'administration étendue restent ouvertes. Les laisser ouvertes est plus fidèle à UP que de les déclarer résolues dans le texte alors que les routes ne les portent pas (Kruchten, 2004 ; Larman, 2004). Le lecteur qui reprend le mémoire par les figures, puis par une session dans le navigateur, doit reconnaître le même système.",
    ])


def plus_annexes(doc, add_h, add_p, add_table):
    add_h(doc, "Annexe K. Écrans du client web", 2)
    _ps(doc, add_p, [
        "L'écran de connexion demande l'adresse et le mot de passe. L'échec y reste affiché. Un lien mène à l'inscription. L'écran d'inscription demande le nom, l'adresse et le mot de passe. Ces deux écrans précèdent la coque. Ils réalisent les cas s'inscrire et s'authentifier, et seulement eux : il n'y a pas de dépôt avant la session.",
        "La coque propose quatre destinations. Le tableau de bord rassemble les cartes d'indicateurs, la répartition par genre, l'histogramme de la semaine et un extrait d'historique. Le coffre rassemble la recherche, les filtres de genre, la grille et l'action de dépôt. L'activité rassemble le journal. Les réglages rassemblent le thème sombre ou clair, l'aperçu, le nom, la corbeille, l'administration conditionnelle et la déconnexion. Le détail d'un fichier s'ouvre depuis le coffre et concentre la restauration. La corbeille s'ouvre depuis le tableau de bord ou les réglages et concentre la remise et la purge.",
        "Cette carte des écrans sert à vérifier qu'aucun écran ne porte un cas interdit. Il n'existe pas d'écran « lire le coffre d'un autre utilisateur ». Il n'existe pas d'écran « déposer sans chiffrer ». Il existe un écran d'administration borné. Si une évolution ajoutait un écran, la question de revue serait la même que pour un cas : quel acteur, quel but, quelle donnée lue. Un écran qui ne répond pas à une ligne du tableau 5 est soit un détail d'un cas existant, soit un hors périmètre.",
    ])
    add_h(doc, "Annexe L. Jeu de données d'illustration", 2)
    _ps(doc, add_p, [
        "Un jeu minimal suffit à remplir les graphiques et l'historique sans prétendre à une charge réelle. Premier compte : l'administrateur de démonstration, déjà chargé, utilisé seulement pour l'annexe d'administration. Deuxième compte : un utilisateur créé par le formulaire, propriétaire des fichiers d'essai. Fichiers suggérés : un court texte, une petite image, un document, une petite archive. Quatre dépôts produisent quatre lignes d'historique, une répartition non vide et au moins une barre sur le jour courant. L'un des quatre est ensuite écarté, afin que la carte corbeille ne reste pas à zéro. L'un est restauré, afin que le journal contienne un téléchargement. L'un est purgé, afin de vérifier la disparition.",
        "Ce jeu ne contient pas de secret réel. Les fichiers sont des exemples. Le mot de passe du compte de test est choisi pour l'essai et n'est pas réutilisé ailleurs. Après les essais E20, le deuxième compte peut avoir été supprimé : il faut alors le recréer pour recommencer E05. L'administrateur de démonstration, lui, doit rester, sinon plus personne ne satisfait le rôle admin et les essais E18 à E21 n'ont plus d'acteur. Cette précaution reprend l'interdit « dernier administrateur », qui n'est pas seulement une règle d'API : c'est aussi une règle d'usage du jeu d'essai.",
        "Les tailles restent petites afin que l'essai soit rapide et que la miniature d'image reste sous la limite du client. Un fichier très volumineux testerait les limites d'envoi de l'API, qui sont un paramètre de construction, non un cas d'utilisation distinct. Si cet essai de taille est tenté, le résultat attendu d'un dépassement est un refus explicite, classé avec les extensions du scénario 2, et non un blob partiel présenté comme une version réussie. Le jeu principal, celui des quatre fichiers, reste néanmoins le jeu de référence du mémoire, parce qu'il couvre les genres, la corbeille et les graphiques sans dépendre du débit du poste.",
    ])
    add_h(doc, "Annexe M. Correspondance finale des chapitres", 2)
    add_table(
        doc,
        ["Chapitre", "Livrable UP", "Figure ou tableau principal"],
        [
            ["1. Revue de littérature", "Exigences et modèle de menace", "Tableau 2, phases UP"],
            ["2. Systèmes existants", "Écart à combler", "Tableaux 1 et 3"],
            ["3. Analyse et conception", "Cas, scénarios, activité, classes", "Figures 1 à 5, tableaux 4 et 5"],
            ["4. Implémentation", "Construction vérifiable", "Tableaux 6 et 7, essai web"],
            ["Annexes", "Fiches, schéma, routes, essais", "Tableaux A1 à M"],
        ],
    )
    add_p(doc, "Tableau M1. Correspondance entre chapitres et livrables", italic=True, center=True, first_line=False)
    _ps(doc, add_p, [
        "La lecture recommandée suit l'ordre des chapitres, puis les annexes lorsque le détail d'une route ou d'un essai est nécessaire. Les figures 1 à 5 se lisent avec les sections 3.8 à 3.16, pas seules. Le tableau M1 sert de carte si l'on cherche un livrable pendant la soutenance : la menace est au chapitre 1, l'écart au chapitre 2, le dessin au chapitre 3, la preuve au chapitre 4. Aucun livrable ne relève d'une autre méthode que le Unified Process, et aucune figure ne relève d'une autre notation que UML, hors la vue d'architecture qui ne fait que placer les composants déjà nommés.",
        "Pour préparer la soutenance, on peut dérouler une seule session et s'arrêter à chaque livrable. On ouvre la figure 1 et l'on montre l'acteur qui se connecte, puis celui qui dépose. On ouvre la figure 2 au moment où le tableau de bord apparaît. On ouvre la figure 3 au moment où le fichier entre dans le coffre. On ouvre la figure 4 seulement si l'on provoque un refus, afin de ne pas laisser croire que le diagramme d'activité répète la séquence. On ouvre la figure 5 pour nommer la version et l'opération qui viennent d'être créées. Ce parcours dure le temps de quelques fichiers du jeu de l'annexe L. Il suffit à montrer que les dessins et le client web parlent du même système.",
        "Les annexes ne sont pas un second mémoire. Elles détaillent ce que les chapitres ont déjà décidé. Si une phrase d'annexe contredisait un scénario, c'est le scénario du chapitre 3 qui primerait, puis la construction devrait être corrigée. L'ordre de vérité retenu est donc le suivant : exigence du chapitre 1, écart du chapitre 2, cas et dessins du chapitre 3, code du chapitre 4, détail en annexe. Cette hiérarchie évite qu'une route ajoutée plus tard devienne, sans le dire, un nouveau cas d'utilisation.",
    ])
    add_h(doc, "Annexe N. Ordre de lecture des figures", 2)
    _ps(doc, add_p, [
        "Figure 1, cas d'utilisation. La lire en commençant par l'acteur Utilisateur, puis par les cas S'authentifier et Sauvegarder un fichier. Repérer l'inclusion vers Chiffrer le fichier : elle part du cas de sauvegarde, elle n'est pas un cas isolé proposé à l'acteur. Repérer ensuite l'acteur Administrateur et le cas Gérer les comptes, sans flèche vers la restauration des fichiers des autres. Cette lecture prend une minute et fixe le périmètre avant les scénarios.",
        "Figure 2, séquence d'authentification. Suivre les flèches de haut en bas. Vérifier que la dérivation de la clé est une boucle sur le client, après la réponse qui apporte le sel. Vérifier qu'aucune flèche de retour ne porte la clé maître. Figure 3, séquence de sauvegarde. Vérifier que le chiffrement précède l'envoi du blob. Les deux figures sont des nominaux : elles ne montrent pas le mot de passe faux ni le fichier illisible.",
        "Figure 4, activité. La lire seulement après la figure 3, comme son complément. Les deux losanges sont les deux questions du cas sauvegarder : le fichier est-il lisible, l'enregistrement est-il accepté. Chaque branche « non » se termine par un message. La branche « oui » se termine par le fichier visible dans le coffre. Figure 5, classes. La lire en partant de Utilisateur, puis en descendant vers Session, Appareil, Fichier, VersionFichier et Operation. S'arrêter sur VersionFichier pour citer le nonce et la clé enveloppée, et pour rappeler ce qui n'y est pas : la clé maître et le clair.",
        "La figure d'architecture, placée au chapitre 4, se lit en dernier. Elle ne contredit pas la figure 5 : elle place le client, l'API et la base qui réalisent ces classes. La clé s'arrête dans le client. Les blobs s'arrêtent sur le disque. Les métadonnées s'arrêtent dans MySQL. Avec cet ordre, un lecteur qui n'a pas suivi la rédaction peut retrouver le fil en six figures, puis revenir aux fiches 3.8 et aux essais de l'annexe G pour le détail des extensions.",
    ])
    add_h(doc, "Annexe O. Conduite pas à pas des essais", 2)
    _ps(doc, add_p, [
        "E01 se fait sur une adresse jamais utilisée. Le formulaire d'inscription est validé. Le résultat attendu n'est pas encore le coffre : c'est la possibilité de se connecter ensuite avec les mêmes valeurs. E02 reprend exactement la même adresse. Le message d'erreur doit apparaître sur l'écran d'inscription, et la table des comptes ne doit pas gagner une seconde ligne pour cette adresse. E03 utilise le compte qui vient d'être créé. Après validation, le tableau de bord remplace le formulaire. E04 se fait de préférence sur une autre tentative, avec le même compte et un mot de passe modifié d'un caractère. L'écran reste celui de la connexion.",
        "E05 dépose un petit fichier texte depuis le coffre. Le fichier apparaît dans la grille, avec un genre de document ou de texte selon le nom et le type. L'historique contient une ligne de sauvegarde réussie. E06 dépose une image de petite taille, aperçu activé dans les réglages. La grille montre une miniature produite sur le poste, pas une vignette calculée par le serveur. E07 dépose une archive ou une vidéo courte. Le genre est visible. Aucune lecture du contenu n'est proposée par l'API. E08 se tente après une déconnexion, en rappelant l'écran de dépôt si la session a été effacée : l'action est refusée et aucune version réussie n'est ajoutée au compte.",
        "E09 ouvre le fichier texte déposé en E05 et lance la restauration. Le navigateur propose le téléchargement du clair, lisible, comparable à l'original. E10 n'est tenté que sur une copie de laboratoire : si l'empreinte stockée ou le blob est altéré, le client refuse de présenter le clair et affiche l'erreur. On ne pratique pas E10 sur le seul exemplaire d'un fichier à conserver. E11 écarte un fichier, vérifie son absence du coffre actif et sa présence dans la corbeille, puis le remet et vérifie le chemin inverse. E12 purge un fichier d'essai. Il disparaît des deux listes. Une nouvelle restauration de cet identifiant n'est plus possible.",
        "E13 consulte l'activité après E05 et E09. Les lignes portent une date, un type compréhensible et un statut. E14 revient au tableau de bord. Les cartes ne sont pas vides, la répartition cite les genres déposés, l'histogramme marque le jour courant. Les chiffres restent cohérents avec la liste du coffre : un fichier purgé n'est plus compté comme actif. E15 change le thème pour le clair, puis revient au sombre. Les fichiers et l'historique ne changent pas. E16 coupe les miniatures. L'image de E06 reste dans le coffre, sans aperçu, jusqu'à ce que l'option soit rouverte.",
        "E17 se connecte avec le compte simple et ouvre les réglages. L'entrée d'administration est absente. E18 se connecte avec le compte administrateur de démonstration. La liste montre les comptes, leurs rôles et des indicateurs, sans action de téléchargement du contenu d'autrui. E19 change le rôle du compte de test, vérifie le nouvel état, puis le ramène à l'état simple si l'essai suivant doit supprimer un utilisateur non admin. E20 supprime ce compte de test après confirmation. Ses fichiers ne sont plus accessibles. E21 demande la suppression du compte administrateur courant, ou du dernier administrateur : l'API refuse et le compte reste. E22 se déconnecte, puis tente une action de coffre. La session n'est plus acceptée. Il faut repasser par E03, après avoir recréé le compte si E20 l'a retiré.",
        "L'ensemble E01 à E22 couvre les nominaux des figures 2 et 3, les branches de la figure 4, la frontière d'acteur de la figure 1 et les interdits de la figure 5 sur la clé maître. Un essai qui échoue se note avec le message affiché, pas seulement avec l'intuition que « cela n'a pas marché ». Le correctif, s'il est nécessaire, doit rétablir le scénario du chapitre 3 sans inventer un cas nouveau. Lorsque les vingt-deux résultats attendus sont obtenus sur le client web, la construction de cette itération peut être considérée comme vérifiée dans le périmètre du mémoire.",
    ])
